Implementação dos teste de CreateTransaction
Vamos-Parcelar-Lift-Learning/Backend pull request #36
Opened 2020-12-06 14:59 UTC by pedro-prp

**Alterações**

- Criada da rota para obter as transações de um usuário.
- Criação da rota para obter dados de apenas um transação de um usuário.
- Criação dos testes unitários para ambas as rotas.

**Print do testes**
![image](https://user-images.githubusercontent.com/32720946/101283611-3c4c2500-37ba-11eb-8680-f16e3e0a2ab2.png)
closes #27

2020-12-09 17:42 UTC, lukassxp commented on src/dtos/ICreateTransactionDTO.ts
> +import { Double } from 'mongodb';
É melhor utilizar as importações de tipos referentes ao typeorm para evitar problemas de tipagem no momento de buscas ao banco de dados.

```import { Double } from 'typeorm';```

2020-12-09 17:42 UTC, lukassxp commented on src/services/CreateTransactionService.spec.ts
> +import { Double, ObjectID } from 'mongodb';
É melhor utilizar as importações de tipos referentes ao typeorm para evitar problemas de tipagem no momento de buscas ao banco de dados.

```import { Double, ObjectID } from 'typeorm';```

2020-12-09 17:42 UTC, lukassxp commented on src/services/CreateTransactionService.spec.ts
> +  const userJose: User = {
Acho que seria interressante criar de fato um usuário através do repositório de usuário, oq acha? No momento não parece necessário mas futuramente pode gerar necessidade de refatoração.

Qual sua opinião sobre isso? Acha que podemos manter assim ou concorda em de fato criar um usuário utilizando o fakeUserRepository?

2020-12-09 18:21 UTC, lukassxp requested changes
Responder as perguntas feitas e realizar as alterações solicitadas

2020-12-09 20:18 UTC, pedro-prp commented on src/dtos/ICreateTransactionDTO.ts
> +import { Double } from 'mongodb';
Alterado

2020-12-09 21:45 UTC, pedro-prp commented on src/services/CreateTransactionService.spec.ts
> +import { Double, ObjectID } from 'mongodb';
Ao tentar trocar, percebi que teria que trocar tbm do schema de User diretamente, mas ao fazer a tentativa recebi o seguinte erro:

![image](https://user-images.githubusercontent.com/32720946/101692270-bac0f500-3a4e-11eb-91d4-d9306466362b.png)

2020-12-09 22:46 UTC, pedro-prp commented on src/services/CreateTransactionService.spec.ts
> +  const userJose: User = {
Resolvido.

2020-12-13 15:01 UTC, lukassxp commented on src/dtos/ICreateTransactionDTO.ts
> +import { Double } from 'mongodb';
Vou fazer o merge do PR e a gente abre uma tarefa de refatoração depois caso seja necessário, acredito que temos que trocar a definição do schema para os imports do TypeORM para não receber erros. Mas posteriormente a gente vê isso.

2020-12-13 15:02 UTC, lukassxp approved these changes

2020-12-13 15:02 UTC, merged