Atualiza README do repositório
Vamos-Parcelar-Lift-Learning/Backend pull request #37
Opened 2020-12-08 13:44 UTC by pedro-prp

**Alterações**

-Atualização dos dados do README do respositório.

Closes #35

2020-12-09 17:55 UTC, lukassxp reviewed
Acho que deve ser adicionada uma breve descrição geral do projeto além de uma descrição mais aprofundada sobre o que o backend se propõe a fazer, como pro exemplo: servir de interface entre o sistema e serviços externos, etc...

2020-12-09 17:55 UTC, lukassxp commented on README.md
> +#### Variáveis de Ambiente
Prefiro a abordagem de criar um arquivo ```.env.example``` e deixa-lo disponivel no git, indicando nesse tópico apenas que deve ser criado um arquivo ```.env``` contendo as mesmas variaveis do ```.env.example``` com seus respectivos valores preenchidos. Caso ache necessário podem ser adicionados comentários no prórpio ```.env.example``` descrevendo para que é utilizada a variavel e como preenche-la corretamente.

2020-12-09 18:06 UTC, lukassxp commented on README.md
>  ### Pacotes necessários
Especificar que não é necessário o docker para rodar o projeto, quem desejar executar localmente o projeto precisa apenas de uma instancia de mongodb que deve ter sua url de acesso especificada no arquivo ```.env```

Acho que como sugestão de como subir uma instancia mongodb rapidamente vale a dica do docker e o comando de criação de um container.

2020-12-09 18:06 UTC, lukassxp commented on README.md
>  ### Pacotes necessários
Especificar versão minima do node para não gerar confusão e alguém tentar rodar como uma versão mt antiga.

2020-12-09 18:22 UTC, lukassxp requested changes
Realizar as alterações solicitadas

2020-12-13 19:32 UTC, pedro-prp commented on README.md
> +#### Variáveis de Ambiente
Resolvido.

2020-12-13 19:32 UTC, pedro-prp commented on README.md
>  ### Pacotes necessários
Resolvido.

2020-12-13 19:32 UTC, pedro-prp commented on README.md
>  ### Pacotes necessários
Resolvido.

2020-12-22 18:28 UTC, lukassxp approved these changes

2020-12-22 18:28 UTC, merged