Atualiza status pagamento
Vamos-Parcelar-Lift-Learning/Backend pull request #38
Opened 2020-12-08 16:17 UTC by RomuloSouza

**Alterações**

- Criadas rota e controller para callback
- Criado service para atualizar a transação
- Criada lógica para buscar o status da transação no participante direto

**Issue Relacionada**

closes #34

2020-12-09 18:15 UTC, lukassxp reviewed
Faltou adicionar o cashback para o usuário caso a transação seja completada após a atualização de seu status para ```aproved```

2020-12-09 18:15 UTC, lukassxp commented on src/services/UpdateTransactionService.ts
> +    transaction.updated_at = new Date();
Não é necessário definir manualmente a data de atualização do registro. Devemos deixar o proprio banco de dados cuidar desses campos indicando que eles são campos auto atualizaveis atraves de decorators nos schemas. Dessa forma: 

```
 @CreateDateColumn()
  created_at: Date;

 @UpdateDateColumn()
 updated_at: Date;
```

2020-12-09 18:17 UTC, lukassxp requested changes
Faltou adicionar o cashback para o usuário caso a transação seja completada após a atualização de seu status para ```aproved```

2020-12-18 22:15 UTC, RomuloSouza commented
@lukassxp as alterações foram realizadas.

Foi criado uma Service para adição de cashback no usuário caso a transação tenha sido aprovada. Também foram criados testes para a funcionalidade.

2020-12-18 22:15 UTC, RomuloSouza commented on src/services/UpdateTransactionService.ts
> +    transaction.updated_at = new Date();
Feito

2020-12-22 18:25 UTC, lukassxp approved these changes

2020-12-22 18:25 UTC, merged